package app.bpartners.geojobs.model.geometry.polygon;

import static java.lang.Math.atan2;

import java.util.function.Supplier;
import lombok.AllArgsConstructor;
import org.locationtech.jts.algorithm.MinimumDiameter;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Point;
import org.locationtech.jts.geom.Polygon;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class PolygonOrientation implements Supplier<Double> {

  private final Polygon polygon;

  @Override
  public Double get() {
    if (polygon == null || polygon.isEmpty()) {
      throw new IllegalArgumentException("Polygon is null or empty");
    }

    // Get coordinates of the exterior ring
    Coordinate[] coordinates = polygon.getExteriorRing().getCoordinates();

    // Compute the centroid
    Point centroid = polygon.getCentroid();
    double centroidX = centroid.getX();
    double centroidY = centroid.getY();

    // Calculate covariance matrix components
    double sumXX = 0.0, sumYY = 0.0, sumXY = 0.0;
    int n = coordinates.length - 1; // Exclude the closing coordinate

    for (int i = 0; i < n; i++) {
      double dx = coordinates[i].x - centroidX;
      double dy = coordinates[i].y - centroidY;
      sumXX += dx * dx;
      sumYY += dy * dy;
      sumXY += dx * dy;
    }

    // Compute continuationOrientation angle using PCA
    return 0.5 * atan2(2 * sumXY, sumXX - sumYY);
  }

  public double angle() {
    var minRect = MinimumDiameter.getMinimumRectangle(polygon);
    Coordinate[] coords = minRect.getCoordinates();

    double dx = coords[1].x - coords[0].x;
    double dy = coords[1].y - coords[0].y;

    return Math.atan2(dy, dx);
  }
}
