name: Detection completion verification IT

on: [ ]

env:
  API_URL: ${{ secrets.DETECTION_API_URL }}
  API_KEY: ${{ secrets.DETECTION_API_KEY }}
  IN_STATUS_PAGE_ID: ${{ secrets.INSTATUS_PAGE_ID }}
  IN_STATUS_API_KEY: ${{ secrets.INSTATUS_API_KEY }}
  IN_STATUS_500_TMPL_ID: ${{ secrets.INSTATUS_500_TMPL_ID }}
  IN_STATUS_RESOLVE_500_TMPL_ID: ${{ secrets.INSTATUS_RESOLVE_500_TMPL_ID }}
jobs:
  detection-completion-verification:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Retrieve detection_e2_id from cache
        id: restore-detection_e2_id
        uses: actions/cache@v4
        with:
          path: detection_e2_id.txt
          key: detection_e2_id-cache-${{ runner.os }}-${{ github.sha }}

      - name: Read detection_e2_id from file
        run: |
          detection_e2_id=$(cat detection_e2_id.txt)
          echo "Reusing detection_e2_id: $detection_e2_id"
          echo "detection_e2_id=$detection_e2_id" >> $GITHUB_ENV

      - name: Send GET /detections/* request for retrieving result
        run: |
          response=$(curl -s -o detection-response.json -w "%{http_code}" -X GET "$API_URL/detections/$detection_e2_id" \
          -H "Content-Type: application/json" \
          -H "x-api-key: $API_KEY")
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -ne 200 ]; then
            echo "Detection request test failed: HTTP error '$response'"
          exit 1
          fi
          
          name=$(jq -r '.step.name' detection-response.json)
          progression=$(jq -r '.step.status.progression' detection-response.json)
          health=$(jq -r '.step.status.health' detection-response.json)
          in_status_api_url="https://api.instatus.com"
          
          incident_list=$(curl -s -X GET "https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents" \
          -H "Authorization: Bearer $IN_STATUS_API_KEY")
          incident_lines=$(echo "$incident_list" | jq -r '
          .[]
          | select(.status != "RESOLVED" and
          (.name == "Internal server error"))
          | "\(.id)|\(.name)|\(.status)"')
          
          
          geoJsonUrl=$(jq -r '.geoJsonUrl' detection-response.json)
          
          if [[ -z "$geoJsonUrl" || "$geoJsonUrl" == "null" ]]; then
            echo "Detection test failed: 'geoJsonUrl' is still empty or null"
            if [[ -n "$incident_lines" ]]; then
              while IFS='|' read -r id incident_name incident_status; do
                echo "Incident : $incident_name ($incident_status)"
                if [[ "$incident_name" != *"Internal server error"* ]]; then
                  in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" -X POST $in_status_api_url/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_500_TMPL_ID \
                  -H "Authorization: Bearer $IN_STATUS_API_KEY")
                  incident_id=$(jq -r '.id' in-status-response.json)
                  echo "InStatus incident identifier: '$incident_id'"
                  exit 1
                fi
              done <<< "$incident_lines"
              exit 1
            fi
          fi
          
          if [[ -n "$incident_lines" ]]; then
            while IFS='|' read -r id incident_name incident_status; do
              if [[ "$incident_name" == "Internal server error" ]]; then
                curl -s -o /dev/null -X POST $in_status_api_url/v2/$IN_STATUS_PAGE_ID/incidents/"$id"/incident-updates/$IN_STATUS_RESOLVE_500_TMPL_ID \
                -H "Authorization: Bearer $IN_STATUS_API_KEY"
                echo "Resolving internal server error incident : $id"
              fi
            done <<< "$incident_lines"
          fi

          echo "Detection test passed: geoJsonUrl='$geoJsonUrl'"
